num1=int(input("enter the 1st Number"))
num2=int(input("enter the 2nd number"))
print("add two numbers")
print(num1+num2)
print("multi two numbers")
print(num1*num2)
print("Div two numbers")
print(num1/num2)
print("sub two numbers")
print(num1-num2)
print("modulo two numbers")
print(num1%num2)
print("compound two numbers")
print(num1//num2)